services:
  frontend:
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/frontend
      - ./tmp/npm:/root/.npm:z
      - node_modules:/usr/src/frontend/node_modules
    stdin_open: true
    restart: always

  api:
    build:
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./api:/usr/src/api
      - node_modules:/usr/src/api/node_modules
